rigid_bodies:
  '2':
     pose: ardrone/pose
     pose2d: ardrone/ground_pose
     child_frame_id: ardrone/base_link
     parent_frame_id: world

  '9':
    pose: pose
    pose2d: ground_pose
    child_frame_id: DJI/base_link
    parent_frame_id: world

    # '8':
    #     pose: calib/pose
    #     pose2d: calib/ground_pose
    #     child_frame_id: calib/base_link
    #     parent_frame_id: map
