rigid_bodies:
  # '2':
  #    pose: wing/pose
  #    pose2d: wing/ground_pose
  #    child_frame_id: wing/base_link
  #    parent_frame_id: map

  '9':
    pose: pose
    pose2d: ground_pose
    child_frame_id: DJI/base_link
    parent_frame_id: world

    # '8':
    #     pose: calib/pose
    #     pose2d: calib/ground_pose
    #     child_frame_id: calib/base_link
    #     parent_frame_id: map
