# 
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '1':
        pose: ardrone2/pose
        pose2d: ardrone2/ground_pose
        child_frame_id: ardrone2/base_link
        parent_frame_id: map
    '2':
        pose: nao_tracker/pose
        pose2d: nao_tracker/ground_pose
        child_frame_id: nao_tracker/base_link
        parent_frame_id: map
